


<h1>Privacy Policy</h1>
<p>Last updated: June 05, 2021</p>
<p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
<p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
<h1>Interpretation and Definitions</h1>
<h2>Interpretation</h2>
<p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
<h2>Definitions</h2>
<p>For the purposes of this Privacy Policy:</p>
<ul>
<li>
<p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
</li>
<li>
<p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to lopez lyncse.</p>
</li>
<li>
<p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
</li>
<li>
<p><strong>Country</strong> refers to: California,  United States</p>
</li>
<li>
<p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
</li>
<li>
<p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
</li>
<li>
<p><strong>Service</strong> refers to the Website.</p>
</li>
<li>
<p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
</li>
<li>
<p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
</li>
<li>
<p><strong>Website</strong> refers to lyncse, accessible from <a href="https://www.lyncse.com" rel="external nofollow noopener" target="_blank">https://www.lyncse.com</a></p>
</li>
<li>
<p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
</li>
</ul>
<h1>Collecting and Using Your Personal Data</h1>
<h2>Types of Data Collected</h2>
<h3>Personal Data</h3>
<p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
<ul>
<li>
<p>Email address</p>
</li>
<li>
<p>Usage Data</p>
</li>
</ul>
<h3>Usage Data</h3>
<p>Usage Data is collected automatically when using the Service.</p>
<p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
<p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
<h3>Tracking Technologies and Cookies</h3>
<p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
<ul>
<li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
<li><strong>Flash Cookies.</strong> Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read "Where can I change the settings for disabling, or deleting local shared objects?" available at <a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_" rel="external nofollow noopener" target="_blank">https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_</a></li>
<li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
</ul>
<p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies: <a href="https://www.privacypolicies.com/blog/cookies/" target="_blank">What Are Cookies?</a>.</p>
<p>We use both Session and Persistent Cookies for the purposes set out below:</p>
<ul>
<li>
<p><strong>Necessary / Essential Cookies</strong></p>
<p>Type: Session Cookies</p>
<p>Administered by: Us</p>
<p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
</li>
<li>
<p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
<p>Type: Persistent Cookies</p>
<p>Administered by: Us</p>
<p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
</li>
<li>
<p><strong>Functionality Cookies</strong></p>
<p>Type: Persistent Cookies</p>
<p>Administered by: Us</p>
<p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
</li>
</ul>
<p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
<h2>Use of Your Personal Data</h2>
<p>The Company may use Personal Data for the following purposes:</p>
<ul>
<li>
<p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>
</li>
<li>
<p><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
</li>
<li>
<p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
</li>
<li>
<p><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
</li>
<li>
<p><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>
</li>
<li>
<p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
</li>
<li>
<p><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
</li>
<li>
<p><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
</li>
</ul>
<p>We may share Your personal information in the following situations:</p>
<ul>
<li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service,  to contact You.</li>
<li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
<li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
<li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
<li><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
<li><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</li>
</ul>
<h2>Retention of Your Personal Data</h2>
<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
<p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
<h2>Transfer of Your Personal Data</h2>
<p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
<p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
<p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
<h2>Disclosure of Your Personal Data</h2>
<h3>Business Transactions</h3>
<p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
<h3>Law enforcement</h3>
<p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
<h3>Other legal requirements</h3>
<p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>
<li>Comply with a legal obligation</li>
<li>Protect and defend the rights or property of the Company</li>
<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
<li>Protect the personal safety of Users of the Service or the public</li>
<li>Protect against legal liability</li>
</ul>
<h2>Security of Your Personal Data</h2>
<p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
<h1>Children's Privacy</h1>
<p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
<h1>Links to Other Websites</h1>
<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
<h1>Changes to this Privacy Policy</h1>
<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
<p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>



























<div class="one_line_col">
<div>
      <span>
            <h1 style="text-decoration: underline;">YouTube Analytics and Reporting API, YouTube Data API, YouTube IFrame Player, Google Fonts</h1>
      </span>
</div>


<p><a href="https://www.youtube.com/t/terms">Youtube Terms Of Service</a></p>
<p><a href="https://policies.google.com/privacy?hl=en-US">Google Privacy Policy</a></p>

  <h2 id="types_of_data">
    Types of Data collected
  </h2>
 

    <p>
      Among the types of Personal Data that this Application collects, by itself or through third parties, there are:
      Data communicated while using the service; Data communicated in order to use the Service; Usage Data.
    </p>

  <p>Complete details on each type of Personal Data collected are provided in the dedicated sections of this privacy policy or by specific explanation texts displayed prior to the Data collection.<br>Personal Data may be freely provided by the User, or, in case of Usage Data, collected automatically when using this Application.<br>Unless specified otherwise, all Data requested by this Application is mandatory and failure to provide this Data may make it impossible for this Application to provide its services. In cases where this Application specifically states that some Data is not mandatory, Users are free not to communicate this Data without consequences to the availability or the functioning of the Service.<br>Users who are uncertain about which Personal Data is mandatory are welcome to contact the Owner.<br>Any use of Cookies – or of other tracking tools – by this Application or by the owners of third-party services used by this Application serves the purpose of providing the Service required by the User, in addition to any other purposes described in the present document and in the Cookie Policy, if available.</p>
  <p>Users are responsible for any third-party Personal Data obtained, published or shared through this Application and confirm that they have the third party's consent to provide the Data to the Owner.</p>
</div>














<div class="one_line_col">
  <h2 id="place_of_processing">Mode and place of processing the Data</h2>
  <h3>Methods of processing</h3>
  <p>The Owner takes appropriate security measures to prevent unauthorized access, disclosure, modification, or unauthorized destruction of the Data.<br>The Data processing is carried out using computers and/or IT enabled tools, following organizational procedures and modes strictly related to the purposes indicated. In addition to the Owner, in some cases, the Data may be accessible to certain types of persons in charge, involved with the operation of this Application (administration, sales, marketing, legal, system administration) or external parties (such as third-party technical service providers, mail carriers, hosting providers, IT companies, communications agencies) appointed, if necessary, as Data Processors by the Owner. The updated list of these parties may be requested from the Owner at any time.</p>
  <h3>Legal basis of processing</h3>
  <p>The Owner may process Personal Data relating to Users if one of the following applies:</p>
  <ul>
    <li>Users have given their consent for one or more specific purposes. Note: Under some legislations the Owner may be allowed to process Personal Data until the User objects to such processing (“opt-out”), without having to rely on consent or any other of the following legal bases. This, however, does not apply, whenever the processing of Personal Data is subject to European data protection law;</li>
    <li>provision of Data is necessary for the performance of an agreement with the User and/or for any pre-contractual obligations thereof;</li>
    <li>processing is necessary for compliance with a legal obligation to which the Owner is subject;</li>
    <li>processing is related to a task that is carried out in the public interest or in the exercise of official authority vested in the Owner;</li>
    <li>processing is necessary for the purposes of the legitimate interests pursued by the Owner or by a third party.</li>
  </ul>
  <p>In any case, the Owner will gladly help to clarify the specific legal basis that applies to the processing, and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a requirement necessary to enter into a contract. </p>
  <h3>Place</h3>
  <p>The Data is processed at the Owner's operating offices and in any other places where the parties involved in the processing are located.<br><br>
Depending on the User's location, data transfers may involve transferring the User's Data to a country other than their own. To find out more about the place of processing of such transferred Data, Users can check the section containing details about the processing of Personal Data.</p>
  <p>Users are also entitled to learn about the legal basis of Data transfers to a country outside the European Union or to any international organization governed by public international law or set up by two or more countries, such as the UN, and about the security measures taken by the Owner to safeguard their Data.<br><br>
If any such transfer takes place, Users can find out more by checking the relevant sections of this document or inquire with the Owner using the information provided in the contact section.</p>
  <h3>Retention time</h3>
  <p>Personal Data shall be processed and stored for as long as required by the purpose they have been collected for.</p>
  <p>Therefore:</p>
  <ul>
    <li>Personal Data collected for purposes related to the performance of a contract between the Owner and the User shall be retained until such contract has been fully performed.</li>
    <li>Personal Data collected for the purposes of the Owner’s legitimate interests shall be retained as long as needed to fulfill such purposes. Users may find specific information regarding the legitimate interests pursued by the Owner within the relevant sections of  this document or by contacting the Owner.</li>
  </ul>
  <p>The Owner may be allowed to retain Personal Data for a longer period whenever the User has given consent to such processing, as long as such consent is not withdrawn. Furthermore, the Owner may be obliged to retain Personal Data for a longer period whenever required to do so for the performance of a legal obligation or upon order of an authority.<br><br>
Once the retention period expires, Personal Data shall be deleted. Therefore, the right of access, the right to erasure, the right to rectification and the right to data portability cannot be enforced after expiration of the retention period.</p>
</div>















<div class="one_line_col">
    <h2 id="use_collected_data">The purposes of processing</h2>
      <p>
        The Data concerning the User is collected to allow the Owner to provide its Service, comply with its legal obligations, respond to enforcement requests, protect its rights and interests (or those of its Users or third parties), detect any malicious or fraudulent activity, as well as the following:
        Displaying content from external platforms and Analytics.
      </p>
     
    <p>For specific information about the Personal Data used for each purpose, the User may refer to the section “Detailed information on the processing of Personal Data”.</p>
  </div>

<div class="one_line_col">
      <h2 id="data_processing_detailed_info">Detailed information on the processing of Personal Data</h2>
      <p>Personal Data is collected for the following purposes and using the following services:</p>
      <ul class="for_boxes">

          <li>
            <div class="box_primary box_10 expand expanded">
              <h3 class="expand-click w_icon_24 policyicon_purpose_8391856">Analytics</h3>
              <div class="expand-content" style="">
                <p>The services contained in this section enable the Owner to monitor and analyze web traffic and can be used to keep track of User behavior.</p>


                  <h4>YouTube Analytics and Reporting API </h4>
                  <div class="wrap">
                    <p>YouTube Analytics and Reporting API is a video content analytics service provided by Google LLC or by Google Ireland Limited, depending on the location this Application is accessed from.</p>

<p>Through this Service, this Application may collect Data directly or indirectly on or from Users’ devices, including by making use of trackers. Users may restrict such access to their Data via the <a href="https://security.google.com/settings/security/permissions" target="_blank" rel="noopener">security settings page</a> provided by Google. Users may ask the Owner for further information about these privacy settings at any time through the contact details provided in this document.</p>

<p>Data collected through the Service may also be used to help third parties deliver interest-based advertising. Users can opt out of third-party interest-based advertising through their device settings or by visiting the <a href="http://optout.networkadvertising.org/?c=1" target="_blank" rel="noopener">Network Advertising Initiative opt-out page</a>.</p>
                  </div>

                    <p>Personal Data processed: Data communicated in order to use the Service; Data communicated while using the service.</p>

                  

                  
<p>Place of processing:
United States
–
<a href="http://www.google.com/policies/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a> – <a href="https://security.google.com/settings/security/permissions" target="_blank" rel="noopener">Opt out</a>;
Ireland
–
<a href="http://www.google.com/policies/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a> – <a href="https://security.google.com/settings/security/permissions" target="_blank" rel="noopener">Opt out</a>.
</p>

                  

                  

                      <p>
      Category of personal information collected according to CCPA: internet information.
    </p>

    <p>This processing constitutes a sale based on the definition under the CCPA. In addition to the information in this clause, the User can find information regarding how to opt out of the sale in the section detailing the rights of Californian consumers.</p>

              </div>
            </div>
          </li>

          <li>
            <div class="box_primary box_10 expand expanded">
              <h3 class="expand-click w_icon_24 policyicon_purpose_8391850">Displaying content from external platforms</h3>
              <div class="expand-content" style="">
                <p>This type of service allows you to view content hosted on external platforms directly from the pages of this Application and interact with them.<br>
This type of service might still collect web traffic data for the pages where the service is installed, even when Users do not use it.</p>


                  <h4>YouTube Data API </h4>
                  <div class="wrap">
                    <p>YouTube Data API is a video content visualization service provided by Google LLC or by Google Ireland Limited, depending on the location this Application is accessed from, that allows this Application to incorporate functions normally executed on YouTube so that Users can watch, find, and manage YouTube content directly on this Application.</p>

<p>Through this Service, this Application may collect Data directly or indirectly on or from Users’ devices, including by making use of Trackers. Users may restrict such access to their Data via the <a href="https://security.google.com/settings/security/permissions" target="_blank" rel="noopener">security settings page</a> provided by Google. Users may ask the Owner for further information about these privacy settings at any time through the contact details provided in this document.</p>

<p>Data collected through the Service may also be used to help third parties deliver interest-based advertising. Users can opt out of third-party interest-based advertising through their device settings or by visiting the <a href="http://optout.networkadvertising.org/?c=1" target="_blank" rel="noopener">Network Advertising Initiative opt-out page</a>.</p>
                  </div>

                    <p>Personal Data processed: Data communicated in order to use the Service; Data communicated while using the service.</p>

                  

                  
<p>Place of processing:
United States
–
<a href="http://www.google.com/policies/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a> – <a href="https://security.google.com/settings/security/permissions" target="_blank" rel="noopener">Opt out</a>;
Ireland
–
<a href="http://www.google.com/policies/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a> – <a href="https://security.google.com/settings/security/permissions" target="_blank" rel="noopener">Opt out</a>.
</p>

                  

                  

                      <p>
      Category of personal information collected according to CCPA: internet information.
    </p>

    <p>This processing constitutes a sale based on the definition under the CCPA. In addition to the information in this clause, the User can find information regarding how to opt out of the sale in the section detailing the rights of Californian consumers.</p>

                  <h4>YouTube IFrame Player </h4>
                  <div class="wrap">
                    <p>YouTube IFrame Player is a video content visualization service provided by Google LLC or by Google Ireland Limited, depending on the location this Application is accessed from, that allows this Application to incorporate content of this kind on its pages.</p>

<p>Through this Service, this Application may collect Data directly or indirectly on or from Users’ devices, including by making use of trackers. Users may restrict such access to their Data via the <a href="https://security.google.com/settings/security/permissions" target="_blank" rel="noopener">security settings page</a> provided by Google. Users may ask the Owner for further information about these privacy settings at any time through the contact details provided in this document.</p>

<p>Data collected through the Service may also be used to help third parties deliver interest-based advertising. Users can opt out of third-party interest-based advertising through their device settings or by visiting the <a href="http://optout.networkadvertising.org/?c=1" target="_blank" rel="noopener">Network Advertising Initiative opt-out page</a>.</p>
                  </div>

                    <p>Personal Data processed: Data communicated in order to use the Service; Data communicated while using the service.</p>

                  

                  
<p>Place of processing:
United States
–
<a href="http://www.google.com/policies/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a> – <a href="https://security.google.com/settings/security/permissions" target="_blank" rel="noopener">Opt out</a>;
Ireland
–
<a href="http://www.google.com/policies/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a> – <a href="https://security.google.com/settings/security/permissions" target="_blank" rel="noopener">Opt out</a>.
</p>

                  

                  

                      <p>
      Category of personal information collected according to CCPA: internet information.
    </p>

    <p>This processing constitutes a sale based on the definition under the CCPA. In addition to the information in this clause, the User can find information regarding how to opt out of the sale in the section detailing the rights of Californian consumers.</p>

                  <h4>Google Fonts </h4>
                  <div class="wrap">
                    <p>Google Fonts is a typeface visualization service provided by Google LLC or by Google Ireland Limited, depending on the location this Application is accessed from, that allows this Application to incorporate content of this kind on its pages.</p>
                  </div>

                    <p>Personal Data processed: Usage Data; various types of Data as specified in the privacy policy of the service.</p>

                  

                  
<p>Place of processing:
United States
–
<a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a>;
Ireland
–
<a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a>.
</p>

                  

                  

                      <p>
      Category of personal information collected according to CCPA: internet information.
    </p>

    <p>This processing constitutes a sale based on the definition under the CCPA. In addition to the information in this clause, the User can find information regarding how to opt out of the sale in the section detailing the rights of Californian consumers.</p>

              </div>
            </div>
          </li>
      </ul>
    </div>








<div class="one_line_col">
  <h2 id="rights_subjects">The rights of Users</h2>
  <p>Users may exercise certain rights regarding their Data processed by the Owner.</p>
  <p>In particular, Users have the right to do the following:</p>

  <ul>
    <li><strong>Withdraw their consent at any time.</strong> Users have the right to withdraw consent where they have previously given their consent to the processing of their Personal Data.</li>
    <li><strong>Object to processing of their Data.</strong> Users have the right to object to the processing of their Data if the processing is carried out on a legal basis other than consent. Further details are provided in the dedicated section below.</li>
    <li><strong>Access their Data.</strong> Users have the right to learn if Data is being processed by the Owner, obtain disclosure regarding certain aspects of the processing and obtain a copy of the Data undergoing processing.</li>
    <li><strong>Verify and seek rectification.</strong> Users have the right to verify the accuracy of their Data and ask for it to be updated or corrected.</li>
    <li><strong>Restrict the processing of their Data.</strong> Users have the right, under certain circumstances, to restrict the processing of their Data. In this case, the Owner will not process their Data for any purpose other than storing it.
</li>
    <li><strong>Have their Personal Data deleted or otherwise removed.</strong> Users have the right, under certain circumstances, to obtain the erasure of their Data from the Owner.</li>
    <li><strong>Receive their Data and have it transferred to another controller.</strong> Users have the right to receive their Data in a structured, commonly used and machine readable format and, if technically feasible, to have it transmitted to another controller without any hindrance. This provision is applicable provided that the Data is processed by automated means and that the processing is based on the User's consent, on a contract which the User is part of or on pre-contractual obligations thereof.</li>
    <li><strong>Lodge a complaint.</strong> Users have the right to bring a claim before their competent data protection authority.</li>
  </ul>

  <h3>Details about the right to object to processing</h3>
  <p>Where Personal Data is processed for a public interest, in the exercise of an official authority vested in the Owner or for the purposes of the legitimate interests pursued by the Owner, Users may object to such processing by providing a ground related to their particular situation to justify the objection.</p>
  <p>Users must know that, however, should their Personal Data be processed for direct marketing purposes, they can object to that processing at any time without providing any justification. To learn, whether the Owner is processing Personal Data for direct marketing purposes, Users may refer to the relevant sections of this document. </p>

  <h3>How to exercise these rights</h3>
  <p>Any requests to exercise User rights can be directed to the Owner through the contact details provided in this document. These requests can be exercised free of charge and will be addressed by the Owner as early as possible and always within one month.</p>
</div>






<div class="one_line_col">
  <h2 id="further_data_processing_info">Additional information about Data collection and processing</h2>
  <h3>Legal action</h3>
  <p>The User's Personal Data may be used for legal purposes by the Owner in Court or in the stages leading to possible legal action arising from improper use of this Application or the related Services.<br>The User declares to be aware that the Owner may be required to reveal personal data upon request of public authorities.</p>
  <h3>Additional information about User's Personal Data</h3>
  <p>In addition to the information contained in this privacy policy, this Application may provide the User with additional and contextual information concerning particular Services or the collection and processing of Personal Data upon request.</p>
  <h3>System logs and maintenance</h3>
  <p>For operation and maintenance purposes, this Application and any third-party services may collect files that record interaction with this Application (System logs) use other Personal Data (such as the IP Address) for this purpose.</p>
  <h3>Information not contained in this policy</h3>
  <p>More details concerning the collection or processing of Personal Data may be requested from the Owner at any time. Please see the contact information at the beginning of this document.</p>

    <h3>How “Do Not Track” requests are handled</h3>
    <p>This Application does not support “Do Not Track” requests.<br>To determine whether any of the third-party services it uses honor the “Do Not Track” requests, please read their privacy policies.</p>

  <h3>Changes to this privacy policy</h3>
  <p>The Owner reserves the right to make changes to this privacy policy at any time by notifying its Users on this page and possibly within this Application and/or - as far as technically and legally feasible - sending a notice to Users via any contact information available to the Owner. It is strongly recommended to check this page often, referring to the date of the last modification listed at the bottom. <br><br>
Should the changes affect processing activities performed on the basis of the User’s consent, the Owner shall collect new consent from the User, where required.</p>

</div>


<div class="one_line_col">
  <h2 id="california_info">Information for Californian consumers</h2>
<p>This part of the document integrates with and supplements the information contained in the rest of the privacy policy and is provided by the business running this Application and, if the case may be, its parent, subsidiaries and affiliates (for the purposes of this section referred to collectively as “we”, “us”, “our”).</p>
<p>The provisions contained in this section apply to all Users who are consumers residing in the state of California, United States of America, according to "The California Consumer Privacy Act of 2018" (Users are referred to below, simply as “you”, “your”, “yours”), and, for such consumers, these provisions supersede any other possibly divergent or conflicting provisions contained in the privacy policy.</p>
<p>This part of the document uses the term “personal information“ as it is defined in The California Consumer Privacy Act (CCPA).</p>

  <h3>Categories of personal information collected, disclosed or sold</h3>
<p>In this section we summarize the categories of personal information that we've collected, disclosed or sold and the purposes thereof. <strong>You can read about these activities in detail in the section titled “Detailed information on the processing of Personal Data” within this document.</strong></p>

<h4>Information we collect: the categories of personal information we collect</h4>
<p>We have collected the following categories of personal information about you: internet information.</p>
<p>We will not collect additional categories of personal information without notifying you.</p>

<h4>How we collect information: what are the sources of the personal information we collect?</h4>
<p>We collect the above mentioned categories of personal information, either directly or indirectly, from you when you use this Application.</p>
<p>For example, you directly provide your personal information when you submit requests via any forms on this Application. You also provide personal information indirectly when you navigate this Application, as personal information about you is automatically observed and collected. 
Finally, we may collect your personal information from third parties that work with us in connection with the Service or with the functioning of this Application and features thereof.</p>

<h4>How we use the information we collect: sharing and disclosing of your personal information with third parties for a business purpose</h4>
<p>We may disclose the personal information we collect about you to a third party for business purposes.
In this case, we enter a written agreement with such third party that requires the recipient to both keep the personal information confidential and not use it for any purpose(s) other than those necessary for the performance of the agreement.</p>
<p>We may also disclose your personal information to third parties when you explicitly ask or authorize us to do so, in order to provide you with our Service.</p>
<p>To find out more about the purposes of processing, please refer to the relevant section of this document.</p>

    <h4>Sale of your personal information</h4>
<p>For our purposes, the word “sale” means any “selling, renting, releasing, disclosing, disseminating, making available, transferring or otherwise communicating orally, in writing, or by electronic means, a consumer's personal information by the business to <strong>another business or a third party, for monetary or other valuable consideration</strong>”.</p>
<p>This means that, for example, a sale can happen whenever an application runs ads, or makes statistical analyses on the traffic or views, or simply because it uses tools such as social network plugins and the like.</p>

<h4>Your right to opt out of the sale of personal information</h4>
<p>You have the right to opt out of the sale of your personal information. This means that whenever you request us to stop selling your data, we will abide by your request.<br>Such requests can be made freely, at any time, without submitting any verifiable request, simply by following the instructions below.</p>

<h4>Instructions to opt out of the sale of personal information</h4>
<p>If you’d like to know more, or exercise your right to opt out in regard to all the sales carried out by this Application, both online and offline, you can contact us for further information using the contact details provided in this document.</p>


  <h4>What are the purposes for which we use your personal information?</h4>
<p>We may use your personal information to allow the operational functioning of this Application and features thereof (“business purposes”). In such cases, your personal information will be processed in a fashion necessary and proportionate to the business purpose for which it was collected, and strictly within the limits of compatible operational purposes.</p>
<p>We may also use your personal information for other reasons such as for commercial purposes (as indicated within the section “Detailed information on the processing of Personal Data” within this document), as well as for complying with the law and defending our rights before the competent authorities where our rights and interests are threatened or we suffer an actual damage.</p>
<p>We will not use your personal information for different, unrelated, or incompatible purposes without notifying you.</p>

  <h3>Your California privacy rights and how to exercise them</h3>

<h4>The right to know and to portability</h4>
<p>You have the right to request that we disclose to you:</p>
<ul>
  <li>the categories and sources of the personal information that we collect about you, the purposes for which we use your information and with whom such information is shared;</li>
  <li>
    in case of sale of personal information or disclosure for a business purpose, two separate lists where we disclose:
    <ul>
      <li>for sales, the personal information categories purchased by each category of recipient; and

</li>
      <li>for disclosures for a business purpose, the personal information categories obtained by each category of recipient.</li>
    </ul>
  </li>
</ul>
<p>The disclosure described above will be limited to the personal information collected or used over the past 12 months.</p>
<p>If we deliver our response electronically, the information enclosed will be "portable", i.e. delivered in an easily usable format to enable you to transmit the information to another entity without hindrance – provided that this is technically feasible.</p>

<h4>The right to request the deletion of your personal information</h4>
<p>You have the right to request that we delete any of your personal information, subject to exceptions set forth by the law (such as, including but not limited to, where the information is used to identify and repair errors on this Application, to detect security incidents and protect against fraudulent or illegal activities, to exercise certain rights etc.).</p>
<p>If no legal exception applies, as a result of exercising your right, we will delete your personal information and direct any of our service providers to do so.</p>

  <h4>How to exercise your rights</h4>
<p>To exercise the rights described above, you need to submit your verifiable request to us by contacting us via the details provided in this document.</p>
<p>For us to respond to your request, it’s necessary that we know who you are. Therefore, you can only exercise the above rights by making a verifiable request which must:</p>
<ul>
  <li>provide sufficient information that allows us to reasonably verify you are the person about whom we collected personal information or an authorized representative;</li>
  <li>describe your request with sufficient detail that allows us to properly understand, evaluate, and respond to it.</li>
</ul>
<p>We will not respond to any request if we are unable to verify your identity and therefore confirm the personal information in our possession actually relates to you.</p>
<p>If you cannot personally submit a verifiable request, you can authorize a person registered with the California Secretary of State to act on your behalf.</p>
<p>If you are an adult, you can make a verifiable request on behalf of a minor under your parental authority.</p>
<p>You can submit a maximum number of 2 requests over a period of 12 months.</p>

  <h4>How and when we are expected to handle your request</h4>
<p>We will confirm receipt of your verifiable request within 10 days and provide information about how we will process your request.</p>
<p>We will respond to your request within 45 days of its receipt. Should we need more time, we will explain to you the reasons why, and how much more time we need. In this regard, please note that we may take up to 90 days to fulfill your request.</p>
<p>Our disclosure(s) will cover the preceding 12 month period.</p>
<p>Should we deny your request, we will explain you the reasons behind our denial.</p>
<p>We do not charge a fee to process or respond to your verifiable request unless such request is manifestly unfounded or excessive. In such cases, we may charge a reasonable fee, or refuse to act on the request. In either case, we will communicate our choices and explain the reasons behind it.</p>


  
</div>




<div class="one_line_col">
  <h2 id="brazil_info">Information for Users residing in Brazil</h2>
<p>This part of the document integrates with and supplements the information contained in the rest of the privacy policy and is provided by the entity running this Application and, if the case may be, its parent, subsidiaries and affiliates (for the purposes of this section referred to collectively as “we”, “us”, “our”).<br> The provisions contained in this section apply to all Users who reside in Brazil, according to the "Lei Geral de Proteção de Dados" (Users are referred to below, simply as “you”, “your”, “yours”). For such Users, these provisions supersede any other possibly divergent or conflicting provisions contained in the privacy policy. <br> This part of the document uses the term “personal information“ as it is defined in the Lei Geral de Proteção de Dados (<strong>LGPD</strong>).</p>

  <h3>The grounds on which we process your personal information</h3>
<p>We can process your personal information solely if we have a legal basis for such processing. Legal bases are as follows:
</p><ul>
<li> your consent to the relevant processing activities;</li>
<li> compliance with a legal or regulatory obligation that lies with us;</li>
<li> the carrying out of public policies provided in laws or regulations or based on contracts, agreements and similar legal instruments;</li>
<li> studies conducted by research entities, preferably carried out on anonymized personal information;</li>
<li> the carrying out of a contract and its preliminary procedures, in cases where you are a party to said contract;</li>
<li> the exercising of our rights in judicial, administrative or arbitration procedures; </li>
<li> protection or physical safety of yourself or a third party;</li>
<li> the protection of health – in procedures carried out by health entities or professionals;</li>
<li> our legitimate interests, provided that your fundamental rights and liberties do not prevail over such interests; and </li>
<li> credit protection.</li>
</ul><p></p>
<p>To find out more about the legal bases, you can contact us at any time using the contact details provided in this document.</p>

  <h3>Categories of personal information processed</h3>
<p>To find out what categories of your personal information are processed, you can read the section titled “Detailed information on the processing of Personal Data” within this document.</p>

  <h3>Why we process your personal information</h3>
<p>To find out why we process your personal information, you can read the sections titled “Detailed information on the processing of Personal Data” and “The purposes of processing” within this document.</p>

  <h3>Your Brazilian privacy rights, how to file a request and our response to your requests</h3>
<h4>Your Brazilian privacy rights</h4>

<p> You have the right to:
</p><ul>
<li>obtain confirmation of the existence of processing activities on your personal information;</li>
<li>access to your personal information;</li>
<li>have incomplete, inaccurate or outdated personal information rectified;</li>
<li>obtain the anonymization, blocking or elimination of your unnecessary or excessive personal information, or of information that is not being processed in compliance with the LGPD;</li>
<li>obtain information on the possibility to provide or deny your consent and the consequences thereof;</li>
<li>obtain information about the third parties with whom we share your personal information;</li>
<li>obtain, upon your express request, the portability of your personal information (except for anonymized information) to another service or product provider, provided that our commercial and industrial secrets are safeguarded;</li>
<li>obtain the deletion of your personal information being processed if the processing was based upon your consent, unless one or more exceptions provided for in art. 16 of the LGPD apply;</li>
<li>revoke your consent at any time;</li>
<li>lodge a complaint related to your personal information with the ANPD (the National Data Protection Authority) or with consumer protection bodies;</li>
<li>oppose a processing activity in cases where the processing is not carried out in compliance with the provisions of the law;</li>
<li>request clear and adequate information regarding the criteria and procedures used for an automated decision; and</li>
<li>request the review of decisions made solely on the basis of the automated processing of your personal information, which affect your interests. These include decisions to define your personal, professional, consumer and credit profile, or aspects of your personality.</li>
</ul><p></p>
<p> You will never be discriminated against, or otherwise suffer any sort of detriment, if you exercise your rights.</p>

<h4>How to file your request</h4>
<p>You can file your express request to exercise your rights free from any charge, at any time, by using the contact details provided in this document, or via your legal representative.</p>

<h4>How and when we will respond to your request</h4>
<p>We will strive to promptly respond to your requests.<br> In any case, should it be impossible for us to do so, we’ll make sure to communicate to you the factual or legal reasons that prevent us from immediately, or otherwise ever, complying with your requests. In cases where we are not processing your personal information, we will indicate to you the physical or legal person to whom you should address your requests, if we are in the position to do so.</p>
<p>In the event that you file an <strong>access</strong> or personal information <strong> processing confirmation</strong> request, please make sure that you specify whether you’d like your personal information to be delivered in electronic or printed form. <br> You will also need to let us know whether you want us to answer your request immediately, in which case we will answer in a simplified fashion, or if you need a complete disclosure instead. <br> In the latter case, we’ll respond within 15 days from the time of your request, providing you with all the information on the origin of your personal information, confirmation on whether or not records exist, any criteria used for the processing and the purposes of the processing, while safeguarding our commercial and industrial secrets.</p>
<p>In the event that you file a <strong>rectification, deletion, anonymization or personal information blocking</strong> request, we will make sure to immediately communicate your request to other parties with whom we have shared your personal information in order to enable such third parties to also comply with your request – except in cases where such communication is proven impossible or involves disproportionate effort on our side.</p>

  <h3>Transfer of personal information outside of Brazil permitted by the law</h3>
<p>We are allowed to transfer your personal information outside of the Brazilian territory in the following cases:
</p><ul>
<li>when the transfer is necessary for international legal cooperation between public intelligence, investigation and prosecution bodies, according to the legal means provided by the international law;</li>
<li>when the transfer is necessary to protect your life or physical security or those of a third party;</li>
<li>when the transfer is authorized by the ANPD;</li>
<li>when the transfer results from a commitment undertaken in an international cooperation agreement;</li>
<li>when the transfer is necessary for the execution of a public policy or legal attribution of public service;</li>
<li>when the transfer is necessary for compliance with a legal or regulatory obligation, the carrying out of a contract or preliminary procedures related to a contract, or the regular exercise of rights in judicial, administrative or arbitration procedures.</li>
</ul><p></p>

  
</div>




<div class="one_line_col">
  <div class="box_primary box_10 definitions expand expanded">
    <h3 id="definitions_and_legal_references" class="expand-click w_icon_24 icon_ribbon">
      Definitions and legal references
    </h3>
    <div class="expand-content" style="">
      <h4>Personal Data (or Data)</h4>
      <p>Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</p>

      <h4>Usage Data</h4>
      <p>Information collected automatically through this Application (or third-party services employed in this Application), which can include: the IP addresses or domain names of the computers utilized by the Users who use this Application, the URI addresses (Uniform Resource Identifier), the time of the request, the method utilized to submit the request to the server, the size of the file received in response, the numerical code indicating the status of the server's answer (successful outcome, error, etc.), the country of origin, the features of the browser and the operating system utilized by the User, the various time details per visit (e.g., the time spent on each page within the Application) and the details about the path followed within the Application with special reference to the sequence of pages visited, and other parameters about the device operating system and/or the User's IT environment.</p>

      <h4>User</h4>
      <p>The individual using this Application who, unless otherwise specified, coincides with the Data Subject.</p>

      <h4>Data Subject</h4>
      <p>The natural person to whom the Personal Data refers.</p>

      <h4>Data Processor (or Data Supervisor)</h4>
      <p>The natural or legal person, public authority, agency or other body which processes Personal Data on behalf of the Controller, as described in this privacy policy.</p>

      <h4>Data Controller (or Owner)</h4>
      <p>The natural or legal person, public authority, agency or other body which, alone or jointly with others, determines the purposes and means of the processing of Personal Data, including the security measures concerning the operation and use of this Application. The Data Controller, unless otherwise specified, is the Owner of this Application.</p>

      <h4>This Application</h4>
      <p>The means by which the Personal Data of the User is collected and processed.</p>

      <h4>Service</h4>
      <p>The service provided by this Application as described in the relative terms (if available) and on this site/application.</p>

      <h4>European Union (or EU)</h4>
      <p>Unless otherwise specified, all references made within this document to the European Union include all current member states to the European Union and the European Economic Area.</p>

      <hr>
      <h4>Legal information</h4>
      <p>This privacy statement has been prepared based on provisions of multiple legislations, including Art. 13/14 of Regulation (EU) 2016/679 (General Data Protection Regulation).</p>
      <p>This privacy policy relates solely to this Application, if not stated otherwise within this document.</p>
    </div>
  </div>
</div>







<h1>Contact Us</h1>
<p>If you have any questions about this Privacy Policy, You can contact us:</p>
<ul>
<li>By email: angellopez@lyncse.com</li>
</ul>